# Configurações de Build (Produção e Branches)
[build]
  command = "npm run build"
  publish = ".next"

# Garante que o plugin do Next.js seja usado
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configurações do Ambiente Local (Netlify Dev)
[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  autoLaunch = false

# --- A MÁGICA ACONTECE AQUI ---
# Configurações ESPECÍFICAS para a branch 'develop'
[context.develop]
  command = "npm run build"

# Aqui nós "ligamos" o modo DEV.
# O Netlify vai injetar essa variável apenas quando estiver na branch develop.
[context.develop.environment]
  NEXT_PUBLIC_USE_DEV_DB = "true"

# (Opcional) Garante também para Deploy Previews (Pull Requests)
[context.deploy-preview.environment]
  NEXT_PUBLIC_USE_DEV_DB = "true"